django_demo/urls.py
# -*- coding: utf-8 -*-
"""
    总的urls配置文件
    定义视图函数相关的URL(网址)  （即规定 访问什么网址对应什么内容）
"""
from learn import views as learn_views
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    # http://127.0.0.1:8000/
    url(r'^$', learn_views.index),

    # http://127.0.0.1:8000/home
    url(r'^home/$', learn_views.home),

    # http://127.0.0.1:8000/add/?b=5
    url(r'^add/$', learn_views.add),

    # 这里的name对应页面的 {% url 'name' 参数 %} 中的name
    url(r'^query/(\d+)/$', learn_views.query, name='query'),

    # 重定向url到new_page/参数
    url(r'^whatever_url/(\d+)/$', learn_views.page_redirect, name='new_query'),
    url(r'^new_page/(\d+)/$', learn_views.new_query, name='new_page'),

    # http://127.0.0.1:8000/template
    url(r'^template/$', learn_views.template),

    # http://127.0.0.1:8000/form 使用form表单
    url(r'^form/$', learn_views.form),
    url(r'^add_form/$', learn_views.add_form),

    # http://127.0.0.1:8000/admin/
    url(r'^admin/', admin.site.urls),


    # http://127.0.0.1:8000/test
    url(r'^test/$', learn_views.test),
    url(r'^test_form/$', learn_views.test_form),

    # http://127.0.0.1:8000/blog_info
    url(r'^blog_info/$', learn_views.query_blog_info),
]

blog/models.py
from django.db import models

# Create your models here.

learn/models.py
from django.db import models

# Create your models here.

people/models.py
"""
    数据库接口相关的接口（QuerySet API)
        从数据库中查询出来的结果一般是一个集合，这个集合叫做QuerySet

    此类作为数据库的对象类
        简单的理解: 继承自models.Model的类 Django自动生成对应的数据库表
            每写一个类
                调用python manage.py makemigrations # 创建migrations用于将models中的类映射成表
                再调用python manage.py migrate # 同步数据库
                相应的会在migrations文件夹中生成建表语句

                会根据appname_classname 生成表名


"""
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


# 新建了一个Person类，继承自models.Model
class Person(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()

    """
        2.7使用def __unicode__(self)
        3.0以上使用def __str__(self)  类似于java的toString方法
    """

    def __str__(self):
        return self.name + str(self.age)


# Blog类，继承自models.Model
class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name


# Entry类，继承自models.Model
class Entry(models.Model):
    blog = models.ForeignKey(Blog)  # 外键 用于关联Blog对象
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    n_comments = models.IntegerField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __str__(self):
        return self.headline


"""
    一篇文章只有一个作者(Author)，
    一个作者可以有多篇文章(Article)，
    一篇文章可以有多个标签（Tag)
"""


# Author作者类，继承自models.Model
@python_2_unicode_compatible
class Author(models.Model):
    name = models.CharField(max_length=50)
    qq = models.CharField(max_length=10)
    address = models.TextField()
    email = models.EmailField()

    def my_property(self):
        return self.name + '===' + self.qq + '===' + self.address + '===' + self.email

    my_property.short_description = "Full name of the person"

    full_name = property(my_property)

    # def __str__(self):
    #     return str(self.name) + " / " + str(self.email)


# Article文章类，继承自models.Model
class Article(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author)  # 多对一
    content = models.TextField()
    score = models.IntegerField()  # 文章的打分
    tags = models.ManyToManyField('Tag')  # 多对多

    def __str__(self):
        return str(self.title) + " / " + str(self.author)


# Tag标签类，继承自models.Model
class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

learn/forms.py
# -*- coding: utf-8 -*-
from django import forms


class AddForm(forms.Form):
    a = forms.IntegerField()
    b = forms.IntegerField()


class AddTestForm(forms.Form):
    name = forms.CharField()
    tag_line = forms.CharField()

blog/views.py
from django.shortcuts import render

# Create your views here.

learn/views.py
# -*- coding: utf-8 -*-
"""
    定义视图函数（访问页面时的内容）
    定义了一个index()函数，第一个参数必须是request(与网页请求有关)
    返回了一个HttpResponse对象
"""
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# 首页
from django.urls import reverse
from learn.forms import AddForm, AddTestForm
from people.models import Blog


def index(request):
    return HttpResponse("Welcome!")


# home页
def home(request):
    """
        使用render时，Django会自动找到settings.py的INSTALLED_APPS所列出的各个app下templates中的文件
    """
    return render(request, 'learn/home.html')


def test(request):
    return render(request, 'learn/test.html')


# 加法
def add(request):
    a = request.GET.get('a', '22')  # 无论有没有传递a 默认都为22
    b = request.GET['b']  # request.GET 类似于一个字典
    c = int(a) + int(b)
    return HttpResponse(str(c))


# 查询第几页
def query(request, page):
    return HttpResponse(str('查询第' + page + '页数据'))


# 页面重定向
def page_redirect(request, page):
    """
        等价于使用{% url 'new_page' 参数 %}
    """
    return HttpResponseRedirect(
        reverse('new_page', args=(page))
    )


# 查询第几页(新)
def new_query(request, page):
    return HttpResponse(str('新页面--查询第' + page + '页数据'))


# 模板页
def template(request):
    """
        使用render时，Django会自动找到settings.py的INSTALLED_APPS所列出的各个app下templates中的文件
    """
    render_dict = {}

    # 单一内容
    render_dict['template_content'] = 'This is template page'

    # 列表
    TutorialList = ["HTML", "CSS", "jQuery", "Python", "Django"]
    render_dict['template_list'] = TutorialList

    # 字典
    info_dict = {'site': '嘿嘿', 'content': '哈哈'}
    render_dict['template_dict'] = info_dict

    # for循环
    lst = map(str, range(10))  # 一个长度为10的List
    render_dict['template_range'] = lst

    return render(request, 'learn/template.html', render_dict)


# 表单页
def form(request):
    form_info = AddForm()
    return render(request, 'learn/form.html', {'form_info': form_info})


# 通过表单调用
def add_form(request):
    if request.method == 'POST':
        # post方式
        form_param = AddForm(request.POST)  # form 包含提交的数据
        if form_param.is_valid():  # 如果提交的数据合法
            a = form_param.cleaned_data['a']
            b = form_param.cleaned_data['b']
            return HttpResponse('This is post method ' + str(int(a) + int(b)))

    elif request.method == 'GET':
        # get方式
        a = request.GET['a']
        b = request.GET['b']
        return HttpResponse('This is get method ' + str(int(a) + int(b)))


def test_form(request):
    form_param = AddTestForm(request.POST)  # form 包含提交的数据
    if form_param.is_valid():  # 如果提交的数据合法
        name = form_param.cleaned_data['name']
        tag_line = form_param.cleaned_data['tag_line']
        b = Blog(name=name, tagline=tag_line)
        b.save()
        return HttpResponse('保存成功~!' + str(name) + str(tag_line))


# 查询blog表的数据
def query_blog_info(request):
    render_dict = {}
    render_dict['blog_info'] = Blog.objects.all()
    return render(request, 'learn/blog_info.html', render_dict)

learn/templates/learn/ad.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

learn/templates/learn/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}默认标题{% endblock %} - Welcome!</title>
</head>
<body>
    {% include 'learn/nav.html' %}

    {% block content %}
        <div>这里是默认内容，所有继承自这个模板的，若不覆盖则显示这里的默认内容</div>
    {% endblock %}

    {% include 'learn/bottom.html' %}

    {% include 'learn/tongji.html' %}

</body>
</html>

learn/templates/learn/blog_info.html
{% extends 'learn/base.html' %}

{% block content %}
    {% include 'learn/ad.html' %}

    <h1>blog表的数据</h1><br/>
    <ui>
        {% for item in blog_info %}
            <li>name为:{{ item.name  }} , tagline为:{{ item.tagline }}</li>
        {% empty %}
            <li>抱歉，列表为空</li>
        {% endfor %}

    </ui>

{% endblock %}

learn/templates/learn/bottom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

learn/templates/learn/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>表单实例</title>
</head>
<body>

    <p>请输入两个数字(get方式)</p>
    <form action="/add_form/" method="get">
        a: <input type="text" name="a"> <br>
        b: <input type="text" name="b"> <br>

        <input type="submit" value="提交">
    </form>


    <p>请输入两个数字(post方式)</p>
    <form action="/add_form/" method="post">
        {% csrf_token %}
        {{ form_info }}
        <input type="submit" value="提交">
    </form>
</body>
</html>

learn/templates/learn/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>欢迎光临首页</title>
</head>
<body>
    <h1>This is home</h1><br/>

    <a href="/add/?b=5">计算22+5</a>

    <p>动态设置网页地址 使用&#123;% url &#x27;name&#x27; 参数 %&#125;</p>

    <a href="{% url 'query' 6 %}">查询</a>

    <!--使用as取别名（相当于定义到nq变量中,之后可以多次使用）-->
    {% url 'new_query' 6 as nq %}

    <a href="{{ nq }}">新查询</a><br/>

    <a href="/template">模板页</a><br/>
    <a href="/form">表单页</a>
</body>
</html>

learn/templates/learn/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>nav</title>
</head>
<body>

</body>
</html>

learn/templates/learn/template.html
{% extends 'learn/base.html' %}

{% block content %}
    {% include 'learn/ad.html' %}

    <h1>模板单一内容String</h1><br/>
    {{ template_content }}


    <h1>模板列表List</h1><br/>
    {% for item in template_list %}
        {{ item }} &nbsp;&nbsp;
    {% endfor %}

    <h1>模板字典Dict(方式一)</h1><br/>
    站点：{{ template_dict.site }} &nbsp;&nbsp;内容：{{ template_dict.content }}

    <h1>模板字典Dict(方式二)</h1><br/>
    <p>{% for key, value in template_dict.items %}
        {{ key }}&nbsp;对应的value&nbsp;{{ value }} <br/>
    {% endfor %}</p>


    <h1>模板if/else使用</h1><br/>

    <!--
        模板标签with，用来定义局部变量。
        无法自定义全局的变量，只能从view中传入全局变量
        赋值语句num="85" 的等号两边不能有空格
    -->
    {% with num=85 %}
        <!-- 比较符号前后必须有至少一个空格！-->
        {% if num >= 90 %}
            成绩优秀，自强学堂你没少去吧！学得不错
        {% elif num >= 80 %}
            成绩良好
        {% elif num >= 70 %}
            成绩一般
        {% elif num >= 60 %}
            需要努力
        {% else %}
            不及格啊，大哥！多去自强学堂学习啊！
        {% endif %}
    {% endwith %}

    <p>
        <!-- 不是最后一项后面加逗号-->
        {% for item in template_range %}
            {% if not forloop.last %}
                {{ item }},
            {% else %}
                {{ item }}
            {% endif %}
        {% endfor %}
    </p>


    <p>
        <!-- 判断 'hello' 在不在List中-->
        {% if 'hello' in template_range%}
            我存在
        {% else %}
            不存在
        {% endif %}
    </p>

    <h1>当列表中可能为空值时</h1><br/>
    <ui>
        {% for item in template_empty %}
            <li>{{ item }}</li>
        {% empty %}
            <li>抱歉，列表为空</li>
        {% endfor %}

    </ui>

{% endblock %}

learn/templates/learn/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试页面</title>
</head>
<body>
    <h1>This is test</h1><br/>
    <form action="/test_form/" method="post">
        {% csrf_token %}
        <div>
            <label class="required" for="id_name">Name:</label>
            <input type="text" name="name" maxlength="30"  required="" id="id_name">
        </div><br/>
        <div>
            <label class="required" for="id_tag_line">Age:</label>
            <input type="text" name="tag_line" required="" id="id_tag_line">
        </div><br/>

        <input type="submit" value="Save" name="_save">
    </form>


    <a href="/blog_info">查询blog</a><br/>
</body>
</html>

learn/templates/learn/tongji.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>